name: Build Caddy with CloudNS Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'  # Latest Go version

    - name: Install xcaddy
      run: |
        curl -sSL https://github.com/caddyserver/xcaddy/releases/download/v0.3.0/xcaddy_0.3.0_linux_amd64.tar.gz | tar -xz -C $HOME/.local/bin

    - name: Build Caddy with CloudNS plugin
      run: |
        xcaddy build --with github.com/caddy-dns/cloudns
      working-directory: ${{ github.workspace }}

    - name: Upload Caddy binary
      uses: actions/upload-artifact@6f2c6b2a6d0ee0fddf9e1a2f9a92d712a1d1303b
      with:
        name: xcaddy
        path: xcaddy
