name: Build Caddy with CloudNS Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install xcaddy
      run: |
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Build Caddy with CloudNS plugin
      run: |
        xcaddy build --with github.com/caddy-dns/cloudns
      working-directory: ${{ github.workspace }}
      
    - name: Upload Caddy binary
      uses: actions/upload-artifact@v2
      with:
        name: caddy
        path: caddy
